language: java
script:
- "./jar.sh"
deploy:
  provider: releases
  api_key:
    secure: b3khsT+ReW1Qs0HDO2GZEgwblZDJTYhRK2saIKqrEusZrkZWiubdQHVIQ9d0X7UfdJU28gmmBDkuHzRa7VgYOgvXkHG64Ras4813+dmf5HRs6UMMnyml9u9kSA7LTxTB7kX7o/jY4b7slLsnZj92Ap9fi9hjPQqCaIjrZsyo5WFakXnLzdkgqJfK/vxGruj+rwm/7OhUPw8MtNd/Rb/SdwJk/GfNCJ7ko7cqf4otFQyix5YDpfbuXjLg/vTm5EHDtHMgfznPmvNjeF1vqL2TtPzTqPEclvtwApK38OGnaC+Ec5r5Hp8/hOSEfwgrcYTOr1oxSih5hyYAUIYrWCH25OGHDDrU8tr0MKEOhB+a7DgfUF07FiJEKWm788UrFW/RgK/BDzo1grqyF/Rva3c7sEkTlMWxWT7gwvShe3VI7jPiTzNFs7Lz7uwC3zPLdUbIWbVjwR6LOIhi2dLqOCepVwBN8XsFC6J/GiN2/bMWTZiBTLyZrjAGpeBf85Nki0ztKdHOlifASeMv3smmJ646Kjo5Z8eqX6U1kOez6CoV223hbB6JhxgdJzbHHaRFblfqz9d1iSTnhTLntPGEtCBHoSo2jVaA1JKKKvu7kGwipVeujbrurU/im9P43LMniGcGgI56gO2EBV7oRmaZ6frCz2V3XklvlhVo3K7lCJcE0j0=
  file: jar/turaco.jar
  on:
    repo: mitchhentges/turaco
